### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by Billccx** [paoliniluis/metabase-trino#3]
```
(base) cuichenxi@cuichenxi-OMEN-Laptop-15-ek0xxx:~/code/metabase-trino$ sudo docker compose up
WARN[0000] The "PWD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PWD" variable is not set. Defaulting to a blank string. 
WARN[0000] /home/cuichenxi/code/metabase-trino/docker-compose.yml: `version` is obsolete 
[+] Running 7/7
 ✔ Container redis-data-1                 Running                                                                           0.0s 
 ✔ Container mongo_5                      Running                                                                           0.0s 
 ✔ Container mysql-data1-trino            Running                                                                           0.0s 
 ✔ Container postgres-data1-trino         Running                                                                           0.0s 
 ✔ Container trino-server                 Running                                                                           0.0s 
 ✔ Container redis-random-data-generator  Created                                                                           0.0s 
 ✔ Container metabase-trino               Created                                                                           0.1s 
Attaching to metabase-trino, mongo_5, mysql-data1-trino, postgres-data1-trino, redis-data-1, redis-random-data-generator, setup-trino, trino-server
metabase-trino               | Adding group `metabase' (GID 2000) ...
metabase-trino               | Done.
metabase-trino               | Adding system user `metabase' (UID 2000) ...
metabase-trino               | Adding new user `metabase' (UID 2000) with group `metabase' ...
metabase-trino               | Not creating home directory `/home/metabase'.
redis-random-data-generator  | 10000 records of type string were generated and inserted [SET] into redis-data-1:6379 in 254ms. 
redis-random-data-generator exited with code 0
metabase-trino               | Warning: environ value jdk-11.0.13+8 for key :java-version has been overwritten with 11.0.13
metabase-trino               | 2024-07-29 08:48:25,624 INFO metabase.util :: Maximum memory available to JVM: 13.8 GB
metabase-trino               | 2024-07-29 08:48:28,402 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
metabase-trino               |  For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
metabase-trino               | 2024-07-29 08:48:29,114 WARN db.env :: WARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. For more information, see https://metabase.com/docs/latest/operations-guide/migrating-from-h2.html
metabase-trino               | Killed
dependency failed to start: container metabase-trino exited (137)

```

Do you have any advice? Would you please tell me how to solve this?

Thanks in advance.

**Comment by paoliniluis** [comment]
seems like PWD (which should be the current directory) is not set. Check my output:
```
luis@pop-os:~$ pwd
/home/luis
luis@pop-os:~$ cd Documents/
luis@pop-os:~/Documents$ pwd
/home/luis/Documents
luis@pop-os:~/Documents$
```

change everywhere where it says PWD to the directory you're working on, or try setting the PWD variable well

**Comment by Billccx** [comment]
> seems like PWD (which should be the current directory) is not set. Check my output:
> 
> ```
> luis@pop-os:~$ pwd
> /home/luis
> luis@pop-os:~$ cd Documents/
> luis@pop-os:~/Documents$ pwd
> /home/luis/Documents
> luis@pop-os:~/Documents$
> ```
> 
> change everywhere where it says PWD to the directory you're working on, or try setting the PWD variable well

Thanks for your reply!

I replaced the $PWD to absoluto pth, but it still not work.

This is my docker-compose.yml:

```
version: '3.9'
services:
  metabase-trino:
    build: 
      context: metabase-starburst/.
    container_name: metabase-trino
    hostname: metabase-trino
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=90
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
     - 3000:3000
    networks: 
      - metanet
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      redis-data-1:
        condition: service_healthy
      postgres-data1-trino:
        condition: service_healthy
      # elasticsearch-data-1:
      #   condition: service_healthy
    cpus: 2
    mem_limit: 512m
  setup-trino:
    image: bash:5.1.16
    container_name: setup-trino
    volumes:
      - /home/cuichenxi/code/metabase-trino/setup:/tmp
    networks:
      - metanet
    depends_on:
      metabase-trino:
        condition: service_healthy
      trino:
        condition: service_healthy
    command: sh /tmp/metabase-setup.sh metabase-trino:3000
    cpus: 1
    mem_limit: 128m
  postgres-data1-trino:
    image: metabase/qa-databases:postgres-sample-12
    container_name: postgres-data1-trino
    hostname: postgres-data1
    networks: 
      - metanet
    cpus: 1
    mem_limit: 128m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d sample"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: -c log_statement=all
  mysql-data1-trino:
    image: metabase/qa-databases:mysql-sample-8
    container_name: mysql-data1-trino
    hostname: mysql-data1
    ports:
    - 3306:3306
    networks: 
      - metanet
    cpus: 1
    mem_limit: 512m
    command: --general-log=1
  redis-data-1:
    image: redis:7
    container_name: redis-data-1
    hostname: redis-data-1
    ports:
      - 6379:6379
    networks: 
      - metanet
    cpus: 1
    mem_limit: 128m
    command: --cluster-enabled no
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 5
  redis-data-generator:
    build: redis-data-generator/.
    container_name: redis-random-data-generator
    hostname: redis-random-data-generator
    volumes:
      - /home/cuichenxi/code/metabase-trino/redis-data-generator:/usr/src/app/
    networks: 
      - metanet
    depends_on:
      redis-data-1:
        condition: service_healthy
    command: node generator.js string 10000 test
  # elasticsearch-data-1:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
  #   container_name: elasticsearch-data-1
  #   hostname: elasticsearch-data-1
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   networks: 
  #     - metanet
  #   cpus: 2
  #   mem_limit: 512m
  #   environment:
  #     - discovery.type=single-node
  #   healthcheck:
  #     test: curl --fail http://localhost:9200/_cluster/health || exit 1
  #     interval: 30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s
  # makelogs:
  #   build: makelogs/.
  #   container_name: makelogs
  #   hostname: makelogs
  #   networks: 
  #     - metanet
  #   depends_on:
  #     elasticsearch-data-1:
  #       condition: service_healthy
  #   command: makelogs -h elasticsearch-data-1:9200
  mongo-data1:
    image: metabase/qa-databases:mongo-sample-5.0
    container_name: mongo_5
    hostname: mongo_5
    networks: 
      - metanet
    cpus: 1
    mem_limit: 128m
  trino:
    image: trinodb/trino:405
    container_name: trino-server
    hostname: trino-server
    volumes: 
    #- /$PWD/trino-server/config.properties:/etc/trino/config.properties
    - /home/cuichenxi/code/metabase-trino/trino-server/config.properties:/etc/trino/config.properties
    #- /$PWD/trino-server/postgres.properties:/etc/trino/catalog/postgres.properties
    - /home/cuichenxi/code/metabase-trino/trino-server/postgres.properties:/etc/trino/catalog/postgres.properties
    #- /$PWD/trino-server/mongodb.properties:/etc/trino/catalog/mongodb.properties
    - /home/cuichenxi/code/metabase-trino/trino-server/mongodb.properties:/etc/trino/catalog/mongodb.properties
    # - /$PWD/trino-server/elasticsearch.properties:/etc/trino/catalog/elasticsearch.properties
    #- /$PWD/trino-server/redis.properties:/etc/trino/catalog/redis.properties
    - /home/cuichenxi/code/metabase-trino/trino-server/redis.properties:/etc/trino/catalog/redis.properties
    #- /$PWD/trino-server/mysql.properties:/etc/trino/catalog/mysql.properties
    - /home/cuichenxi/code/metabase-trino/trino-server/mysql.properties:/etc/trino/catalog/mysql.properties
    restart: always
    ports:
      - 8443:8443
    networks:
      - metanet
    cpus: 2
    mem_limit: 1024m
    healthcheck:
      test: /usr/lib/trino/bin/health-check
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
networks: 
  metanet:
    driver: bridge
```

Would you please give me some advice? Thanks
